### ISSUE TITLE
About TypeError: narrow(): argument 'length' (position 3) must be int, not Tensor

### ISSUE THREAD

**Issue by lizhuding** [milesial/Pytorch-UNet#125]
Hi ,when I run train.py, I met such an error, if  anyone also met?

Epoch 1/10:   0%|                                                                                           | 0/3300 [00:00<?, ?img/s]/home/CN/zizhang.wu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/upsampling.py:122: UserWarning: nn.Upsampling is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate instead.")

Traceback (most recent call last):
  File "train.py", line 172, in <module>
    val_percent=args.val / 100)
  File "train.py", line 77, in train_net
    masks_pred = net(imgs)
  File "/home/CN/wu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/nfs/04_centerNet/CenterNet-master_dlz_segmentation/Pytorch-UNet-master/unet/unet_model.py", line 32, in forward
    x = self.up1(x5, x4)
  File "/home/CN/wu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/nfs/04_centerNet/CenterNet-master_dlz_segmentation/Pytorch-UNet-master/unet/unet_parts.py", line 61, in forward
    diffY // 2, diffY - diffY // 2])
  File "/home/CN/wu/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 2159, in pad
    return ConstantPadNd.apply(input, pad, value)
  File "/home/CN/wu/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/padding.py", line 42, in forward
    c_output = c_output.narrow(i, 0, c_output.size(i) - p[1])
TypeError: narrow(): argument 'length' (position 3) must be int, not Tensor

**Comment by milesial** [comment]
Fixed by https://github.com/milesial/Pytorch-UNet/pull/167
