### ISSUE TITLE
I have some problem

### ISSUE THREAD

**Issue by flj19951219** [milesial/Pytorch-UNet#155]
Traceback (most recent call last):
  File "D:/code/Pytorch-UNet-master/train.py", line 180, in <module>
    val_percent=args.val / 100)
  File "D:/code/Pytorch-UNet-master/train.py", line 66, in train_net
    for batch in train_loader:
  File "C:\Users\asus\Anaconda3\envs\pytorch1.4p3.7\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "C:\Users\asus\Anaconda3\envs\pytorch1.4p3.7\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()
  File "C:\Users\asus\Anaconda3\envs\pytorch1.4p3.7\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\asus\Anaconda3\envs\pytorch1.4p3.7\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\asus\Anaconda3\envs\pytorch1.4p3.7\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\asus\Anaconda3\envs\pytorch1.4p3.7\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\asus\Anaconda3\envs\pytorch1.4p3.7\lib\site-packages\torch\utils\data\dataset.py", line 256, in __getitem__
    return self.dataset[self.indices[idx]]
  File "D:\code\Pytorch-UNet-master\utils\dataset.py", line 50, in __getitem__
    f'Either no mask or multiple masks found for the ID {idx}: {mask_file}'
AssertionError: Either no mask or multiple masks found for the ID 351c583eabd6_14: []

**Comment by milesial** [comment]
Do you have a mask in the masks folder which filename begins with `351c583eabd6_14` ?

**Comment by manvirvirk** [comment]
i m getting same error

**Comment by manvirvirk** [comment]
@flj19951219  you img _ids and masks should be same.

**Comment by cccFox** [comment]
change '*' to your image format(FOR ME is'.jpg')
def __getitem__(self, i):
        idx = self.ids[i]
        mask_file = glob(self.masks_dir + idx + '.jpg')
        img_file = glob(self.imgs_dir + idx + '.jpg')

**Comment by picEmily** [comment]
@flj19951219 
change as following:
mask_file = glob(self.masks_dir +‘/’+ idx + '.jpg')
img_file = glob(self.imgs_dir + '/'+idx + '.jpg')

it is ok.

**Comment by Macc520** [comment]
> @ flj19951219 您的img _id和掩码应该相同。

can i ask you how to solve this problem? PLZ!!!

**Comment by Macc520** [comment]
> i m getting same error

me,too.i want to ask you how to solve this problem,
plz!!!!!

**Comment by Macc520** [comment]
> Do you have a mask in the masks folder which filename begins with `351c583eabd6_14` ?

thanks to you,first .then i meet the same problem.i don't know how to solve.my dataset is （DRIVE）Retinal vessels。 Maybe is the reason of Dataset.

**Comment by sxdisstorng** [comment]
Hi, I encountered same issue whilst I do have mask under the same name. I have changed both image and mask to jpg format and this does not alleviate the issue.

**Comment by AlexanderHustinx** [comment]
You just have to make sure the path to your directories is correct, and it should end on "/"

e.g. 
`imgs_dir="../data/carvana-image-masking-challenge/"`
`masks_dir="../data/carvana-image-masking-challenge/train_masks/"`

**Comment by mostafiz67** [comment]
@flj19951219 could you tell me, how you solve the error? I am also getting the same error!

**Comment by RuoyuX-2018** [comment]
line 12 in dataset.py
def __init__(self, imgs_dir, masks_dir, scale=1, mask_suffix=''):
should change the mask_suffix according to the name of your mask

**Comment by milesial** [comment]
Closing, as this issue is now outdated after the recent code refactor.
