### ISSUE TITLE
inconsistent tensor size

### ISSUE THREAD

**Issue by zishuilli** [milesial/Pytorch-UNet#168]
Traceback (most recent call last):
  File "F:/pycharm/Pytorch-UNet-master/train.py", line 181, in <module>
    val_percent=args.val / 100)
  File "F:/pycharm/Pytorch-UNet-master/train.py", line 98, in train_net
    val_score = eval_net(net, val_loader, device)
  File "F:\pycharm\Pytorch-UNet-master\eval.py", line 29, in eval_net
    tot += dice_coeff(pred, true_masks).item()
  File "F:\pycharm\Pytorch-UNet-master\dice_loss.py", line 40, in dice_coeff
    s = s + DiceCoeff().forward(c[0], c[1])
  File "F:\pycharm\Pytorch-UNet-master\dice_loss.py", line 11, in forward
    self.inter = torch.dot(input.view(-1), target.view(-1))
RuntimeError: inconsistent tensor size, expected tensor [16384] and src [49152] to have the same number of elements, but got 16384 and 49152 elements respectively

**Comment by milesial** [comment]
Can you tell me the sizes of the input and the target? You may load your masks incorrectly.

**Comment by XuesenYang** [comment]
I catch the same bug, how do you handle it?

**Comment by XuesenYang** [comment]
I have solve this bug, as what it point out, I found the second dimension of pred=[1,1, 418,418] is different from true_masks[1,3,418,418].  Because my mask input is [418,418,3]. So, the first way is to use 1 channel mask input, or add one line  code on file eval.py -->  true_masks = true_masks[:, :1, :, :]
