### ISSUE TITLE
Problem occurs when I run predict.py

### ISSUE THREAD

**Issue by wyzjack** [milesial/Pytorch-UNet#17]
Loading model MODEL.pth
Using CUDA version of the net, prepare your GPU !
Model loaded !

Predicting image ap3.jpg ...
Traceback (most recent call last):
  File "predict.py", line 154, in <module>
    use_gpu=not args.cpu)
  File "predict.py", line 42, in predict_img
    output_left = net(X_left)
  File "/home/shushi16/miniconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shushi16/wyz/Pytorch-UNet/unet/unet_model.py", line 26, in forward
    x = self.up2(x, x3)
  File "/home/shushi16/miniconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shushi16/wyz/Pytorch-UNet/unet/unet_parts.py", line 68, in forward
    x = torch.cat([x2, x1], dim=1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 84 and 83 in dimension 2 at /opt/conda/conda-bld/pytorch_1524577177097/work/aten/src/THC/generic/THCTensorMath.cu:111

**Comment by milesial** [comment]
Hi, what are the dimensions of the image `ap3.jpg` ? There might be a problem with the downsampling if it is not divisible by 2.

**Comment by wyzjack** [comment]
width1024 height 683  I suppose it should be OK?

**Comment by wyzjack** [comment]
thank god I finally figure out the problem. 'cause I am using python 2 , -1/2=-1 in python2, while -1/2=-0.5 in python3 this will cause difference in the padding process in the file unet_parts.py 
To solve the problem I just add 'from __future__ import division' at the beginning of the file


thanks

**Comment by milesial** [comment]
Nice catch ! It is indeed a python3 project. I would advise you to use an even width and an even height too to avoid problems.
