### ISSUE TITLE
Incompatibility with Python2.7

### ISSUE THREAD

**Issue by vtddggg** [milesial/Pytorch-UNet#21]
I found your code can only run on Python3. When I run on Python2, some thing strange happened...

```
[root@iZuf67ye1557dce2pbylevZ Pytorch-UNet-master]# python2 train.py -g

    Starting training:
        Epochs: 5
        Batch size: 10
        Learning rate: 0.1
        Training size: 131639
        Validation size: 6928
        Checkpoints: True
        CUDA: True

Starting epoch 1/5.
Killed
```

Can you extend the compatibility of the code on Python2 
Really thank you for your help ！！

**Comment by vtddggg** [comment]
When I run `predict.py` the error message is:

```
Loading model MODEL.pth
Using CUDA version of the net, prepare your GPU !
Model loaded !

Predicting image image.jpg ...
Traceback (most recent call last):
  File "predict.py", line 153, in <module>
    use_gpu=not args.cpu)
  File "predict.py", line 41, in predict_img
    output_left = net(X_left)
  File "/usr/lib64/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/disk2/bake/Pytorch-UNet-master/unet/unet_model.py", line 25, in forward
    x = self.up1(x5, x4)
  File "/usr/lib64/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/disk2/bake/Pytorch-UNet-master/unet/unet_parts.py", line 68, in forward
    x = torch.cat([x2, x1], dim=1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 20 and 19 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:111

```

Maybe down sample or up sample Layer are different in Python2 and Python3 for torch 0.4.0

**Comment by milesial** [comment]
Hi, this project was created for python 3. As for your error, you can check issue #17 , where the problem was fixed for python 2 by adding `from future import division` at the beginning of the file.

**Comment by vtddggg** [comment]
Thank you！
