### ISSUE TITLE
cannot find mask file for traning model

### ISSUE THREAD

**Issue by jie666-6** [milesial/Pytorch-UNet#235]
The target images and masks have been put into folder data\imgs and data\masks separately. But when I run python train.py, it cannot find the corresponding masks which are already in the data\masks. Anyone could help? Thanks

(Pytorch-UNet-master) E:\Pytorch-UNet-master\Pytorch-UNet-master>python train.py
INFO: Using device cuda
INFO: Network:
        3 input channels
        1 output channels (classes)
        Bilinear upscaling
INFO: Creating dataset with 5088 examples
INFO: Starting training:
        Epochs:          5
        Batch size:      1
        Learning rate:   0.0001
        Training size:   4580
        Validation size: 508
        Checkpoints:     True
        Device:          cuda
        Images scaling:  0.5

Epoch 1/5:   0%|                                                                             | 0/4580 [00:09<?, ?img/s]
Traceback (most recent call last):
  File "train.py", line 180, in <module>
    val_percent=args.val / 100)
  File "train.py", line 66, in train_net
    for batch in train_loader:
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\Pytorch-UNet-master\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\Pytorch-UNet-master\lib\site-packages\torch\utils\data\dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\Pytorch-UNet-master\lib\site-packages\torch\utils\data\dataloader.py", line 1014, in _process_data
    data.reraise()
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\Pytorch-UNet-master\lib\site-packages\torch\_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\Pytorch-UNet-master\lib\site-packages\torch\utils\data\_utils\worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\Pytorch-UNet-master\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\Pytorch-UNet-master\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\Pytorch-UNet-master\lib\site-packages\torch\utils\data\dataset.py", line 257, in __getitem__
    return self.dataset[self.indices[idx]]
  File "E:\Pytorch-UNet-master\Pytorch-UNet-master\utils\dataset.py", line 51, in __getitem__
    f'Either no mask or multiple masks found for the ID {idx}: {mask_file}'
AssertionError: Either no mask or multiple masks found for the ID 0d53224da2b7_01: []

**Comment by jie666-6** [comment]
For the training.py, it should use CarvanaDataset instead of BasicDataset.
