### ISSUE TITLE
Help with training on CARVANA images and masks

### ISSUE THREAD

**Issue by rtrahms** [milesial/Pytorch-UNet#242]
Windows 10/Python 3.8/Pytorch 1.7/CUDA 11.1/NVidia GeForce 1080 Ti w/12 GB

Downloaded CARVANA training images and masks, updated train.py to point to those folders.

python train.py 

Starts, but exception thrown shortly thereafter.  Trace below.  I suspect I don't have enough memory, but not sure.

INFO: Using device cuda
INFO: Network:
        3 input channels
        1 output channels (classes)
        Bilinear upscaling
INFO: Creating dataset with 1 examples
INFO: Starting training:
        Epochs:          5
        Batch size:      8
        Learning rate:   0.0001
        Training size:   1
        Validation size: 0
        Checkpoints:     True
        Device:          cuda
        Images scaling:  0.5

Epoch 1/5:   0%|                                                                                                                                                                                                   | 0/1 [00:00<?, ?img/s]T
raceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\python386\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\python386\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\python386\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\python386\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\python386\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\python386\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\python386\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\DATA\Git_Repositories\Pytorch-UNet-master\train.py", line 7, in <module>
    import torch
  File "C:\python386\lib\site-packages\torch\__init__.py", line 117, in <module>
    raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\python386\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\python386\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\python386\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\python386\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\python386\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\python386\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\python386\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\python386\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\DATA\Git_Repositories\Pytorch-UNet-master\train.py", line 7, in <module>
    import torch
  File "C:\python386\lib\site-packages\torch\__init__.py", line 117, in <module>
    raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\python386\lib\site-packages\torch\lib\cudnn_cnn_infer64_8.dll" or one of its dependencies.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\python386\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\python386\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\python386\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\python386\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\python386\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\python386\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\python386\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\DATA\Git_Repositories\Pytorch-UNet-master\train.py", line 7, in <module>
    import torch
  File "C:\python386\lib\site-packages\torch\__init__.py", line 117, in <module>
    raise err

**Comment by milesial** [comment]
It seems that it is an error at the pytorch initialisation. Are you able to load and use pytorch in any other script?

**Comment by rtrahms** [comment]
@milesial -
Yes, that was the issue.  I switched to an environment that I have used pytorch before, and have made it past that error.  Now I am on to the next issue, which is failing to find a mask (that is confirmed to be in the folder)...

INFO: Using device cuda
INFO: Network:
        3 input channels
        1 output channels (classes)
        Bilinear upscaling
INFO: Creating dataset with 5088 examples
INFO: Starting training:
        Epochs:          5
        Batch size:      1
        Learning rate:   0.0001
        Training size:   4580
        Validation size: 508
        Checkpoints:     True
        Device:          cuda
        Images scaling:  0.5

Epoch 1/5:   0%|                                                                                                                                                                                                | 0/4580 [00:10<?, ?img/s]
Traceback (most recent call last):
  File "train.py", line 174, in <module>
    train_net(net=net,
  File "train.py", line 66, in train_net
    for batch in train_loader:
  File "C:\python_envs\pytorch_test1\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "C:\python_envs\pytorch_test1\lib\site-packages\torch\utils\data\dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "C:\python_envs\pytorch_test1\lib\site-packages\torch\utils\data\dataloader.py", line 1014, in _process_data
    data.reraise()
  File "C:\python_envs\pytorch_test1\lib\site-packages\torch\_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\python_envs\pytorch_test1\lib\site-packages\torch\utils\data\_utils\worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\python_envs\pytorch_test1\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\python_envs\pytorch_test1\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\python_envs\pytorch_test1\lib\site-packages\torch\utils\data\dataset.py", line 257, in __getitem__
    return self.dataset[self.indices[idx]]
  File "C:\DATA\Git_Repositories\Pytorch-UNet-master\utils\dataset.py", line 50, in __getitem__
    assert len(mask_file) == 1, \
AssertionError: Either no mask or multiple masks found for the ID 6ae670e86620_16: []

**Comment by milesial** [comment]
Did you correctly switch to using the CarvanaDataset class?

**Comment by rtrahms** [comment]
I'm not following.  I placed the Carvana images in a folder named data/train_imgs, and the associated mask files in a folder named data/train_masks.  I created a checkpoints folder and then ran python train.py.  Was there something else I needed to do?
Thanks

**Comment by rtrahms** [comment]
Installed CPU version of torch, torchvision and torchaudio, back to the same error:

(pytorch_test1) C:\DATA\Git_Repositories\Pytorch-UNet-master>python train.py
INFO: Using device cpu
INFO: Network:
        3 input channels
        1 output channels (classes)
        Bilinear upscaling
INFO: Creating dataset with 5088 examples
INFO: Starting training:
        Epochs:          5
        Batch size:      1
        Learning rate:   0.0001
        Training size:   4580
        Validation size: 508
        Checkpoints:     True
        Device:          cpu
        Images scaling:  0.5

Epoch 1/5:   0%|                                                                                                                                                                                              | 0/4580 [00:10<?, ?img/s]
Traceback (most recent call last):
  File "train.py", line 174, in <module>
    train_net(net=net,
  File "train.py", line 66, in train_net
    for batch in train_loader:
  File "C:\python_envs\pytorch_test1\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "C:\python_envs\pytorch_test1\lib\site-packages\torch\utils\data\dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "C:\python_envs\pytorch_test1\lib\site-packages\torch\utils\data\dataloader.py", line 1111, in _process_data
    data.reraise()
  File "C:\python_envs\pytorch_test1\lib\site-packages\torch\_utils.py", line 428, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\python_envs\pytorch_test1\lib\site-packages\torch\utils\data\_utils\worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\python_envs\pytorch_test1\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\python_envs\pytorch_test1\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\python_envs\pytorch_test1\lib\site-packages\torch\utils\data\dataset.py", line 272, in __getitem__
    return self.dataset[self.indices[idx]]
  File "C:\DATA\Git_Repositories\Pytorch-UNet-master\utils\dataset.py", line 50, in __getitem__
    assert len(mask_file) == 1, \
AssertionError: Either no mask or multiple masks found for the ID 0eeaf1ff136d_06: []

**Comment by milesial** [comment]
I think your memory is toi small for page-locked memory. Try changing to pin_memory=False in train.py for the dataloaders.

**Comment by rtrahms** [comment]
@milesial -
I modified the following lines related to your comment:

    #train_loader = DataLoader(train, batch_size=batch_size, shuffle=True, num_workers=8, pin_memory=True)
    #val_loader = DataLoader(val, batch_size=batch_size, shuffle=False, num_workers=8, pin_memory=True, drop_last=True)
    train_loader = DataLoader(train, batch_size=batch_size, shuffle=True, num_workers=8, pin_memory=False)
    val_loader = DataLoader(val, batch_size=batch_size, shuffle=False, num_workers=8, pin_memory=False, drop_last=True)

Same error.  A clue: the CPU version of torch/torchvision/torchaudio works with or without the pin_memory mod, albeit very slowly.

**Comment by milesial** [comment]
Then your memory is not enough for this scale of images, you can try with a lower scale or use a GPU with more memory.
Closing this because it is related to your setup.

**Comment by rtrahms** [comment]
@milesial - FYI, I did eventually figure this out!  In addition to setting pin_memory=False in the DataLoader class, I reduced the number of workers from 8 to 1.  Started working.  Thanks for the help.
Rob

**Comment by Schweizliu** [comment]
> @milesial - FYI, I did eventually figure this out! In addition to setting pin_memory=False in the DataLoader class, I reduced the number of workers from 8 to 1. Started working. Thanks for the help. Rob

Hello, may I ask for your advice,I drop num_workers to 0 or I get an OSError: [WinError 1455] error, and pin_memory is also set to False. What should I do?
