### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by dufan175** [milesial/Pytorch-UNet#279]
Hello,thanks for your code, but when i run first epoch, it interrupt ，i don't know why:
Epoch 1/100: 100%|██████████████████| 90/90 [00:38<00:00,  2.38img/s, loss (batch)=0.402INFO: Validation Dice Coeff: 0.28414225205779076                                          
Epoch 1/100: 100%|██████████████████| 90/90 [00:46<00:00,  1.95img/s, loss (batch)=0.402]
Traceback (most recent call last):
  File "train.py", line 180, in <module>
    val_percent=args.val / 100)
  File "train.py", line 108, in train_net
    writer.add_images('images', imgs, global_step)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/tensorboard/writer.py", line 589, in add_images
    image(tag, img_tensor, dataformats=dataformats), global_step, walltime)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/tensorboard/summary.py", line 376, in image
    tensor = convert_to_HWC(tensor, dataformats)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/tensorboard/_utils.py", line 107, in convert_to_HWC
    tensor_CHW = make_grid(tensor_NCHW)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/tensorboard/_utils.py", line 76, in make_grid
    assert I.ndim == 4 and I.shape[1] == 3
AssertionError

**Comment by milesial** [comment]
Closing, as this issue is now outdated after the recent code refactor.

**Comment by Victor-0220-yy** [comment]
AssertionError: Caught AssertionError in DataLoader worker process 0.
excuse me ,I 'm trying to finish your project but there is a problem named 'AssertionError',could you please tell me how to deal with it .
![image](https://user-images.githubusercontent.com/74761231/163379395-4f4c93e4-c2bb-4a60-9362-5101e2a90086.png)
![image](https://user-images.githubusercontent.com/74761231/163379475-1db42a06-e55b-44b7-904e-14eee824fa9c.png)
