### ISSUE TITLE
Trying to use it with other dataset. 

### ISSUE THREAD

**Issue by bermudezarii** [milesial/Pytorch-UNet#29]
Hello! 
I am using this project for segmenting teeth, and my dataset has different size that the original one, so that gives me this error. 

` "Please ensure they have the same size.".format(target.size(), input.size()))
Traceback (most recent call last):
  File "train.py", line 161, in <module>
    img_scale=args.scale)
  File "train.py", line 102, in train_net
    loss = criterion(masks_probs_flat, true_masks_flat)
  File "/home/miuser/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/miuser/.local/lib/python3.5/site-packages/torch/nn/modules/loss.py", line 486, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/home/miuser/.local/lib/python3.5/site-packages/torch/nn/functional.py", line 1597, in binary_cross_entropy
    "!= input nelement ({})".format(target.nelement(), input.nelement()))
ValueError: Target and input must have the same number of elements. target nelement (1267876) != input nelement (1254400)
`

Does someone know what I have to change and where?, so this could work with my dataset.

Thanks!

**Comment by bermudezarii** [comment]
What I meant with different size, are the images, different height and width. (:

**Comment by bermudezarii** [comment]
Hi, I was trying to understand more the problem, looks like when I am in train.py

`masks_pred = net(imgs)`

imgs have the size wanted, but the masks_pred has like 3 more pixels, after being processed in the neural network. 

This is with the dataset of carvana: 


`true_masks: torch.Size([4, 640, 640])
masks_pred: torch.Size([4, 1, 640, 640])
masks_prob: torch.Size([4, 1, 640, 640])`

But with my dataset: 


`true_masks: torch.Size([4, 563, 563])
masks_pred: torch.Size([4, 1, 560, 560])

/home/miuser/.local/lib/python3.5/site-packages/torch/nn/functional.py:1006: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")

masks_prob: torch.Size([4, 1, 560, 560])
`

Thanks for the fast answer. I appreciate that.

**Comment by bermudezarii** [comment]
In the unet_model I have this
`def forward(self, x):
        print("\n\n\n\ncreo que es aqui :v\n\n\n\n")
        print("shape x: " + str(x.size()))
        x1 = self.inc(x)
        print("shape x1: " + str(x1.size()))
        x2 = self.down1(x1)
        print("shape x2: " + str(x2.size()))
        x3 = self.down2(x2)
        print("shape x3: " + str(x3.size()))
        x4 = self.down3(x3)
        print("shape x4: " + str(x4.size()))
        x5 = self.down4(x4)
        print("shape x5: " + str(x5.size()))
        x = self.up1(x5, x4)
        print("shape x: " + str(x.size()))
        x = self.up2(x, x3)
        print("shape x: " + str(x.size()))
        x = self.up3(x, x2)
        print("shape x: " + str(x.size()))
        x = self.up4(x, x1)
        print("shape x: " + str(x.size()))
        x = self.outc(x)
        print("shape x last: " + str(x.size()))
        return x
`

Output: 
`shape x: torch.Size([4, 3, 563, 563])
shape x1: torch.Size([4, 64, 563, 563])
shape x2: torch.Size([4, 128, 281, 281])
shape x3: torch.Size([4, 256, 140, 140])
shape x4: torch.Size([4, 512, 70, 70])
shape x5: torch.Size([4, 512, 35, 35])
shape x: torch.Size([4, 256, 70, 70])
shape x: torch.Size([4, 128, 140, 140])
shape x: torch.Size([4, 64, 280, 280])
shape x: torch.Size([4, 64, 560, 560])
shape x last: torch.Size([4, 1, 560, 560])`

**Comment by bermudezarii** [comment]
Perfect, I'll tell you how was it after this. 

Thanks!
