### ISSUE TITLE
Prediction for multi-class segmentation

### ISSUE THREAD

**Issue by MiltonAltSan** [milesial/Pytorch-UNet#344]
After training for a 5 class segmentation, when trying to run the predict.py script (having already changed the n_channels and n_classes to the same used during training), and using one of the RGB images used during training, I get the following error:

Traceback (most recent call last):
  File "predict.py", line 100, in <module>
    mask = predict_img(net=net,
  File "predict.py", line 40, in predict_img
    full_mask = tf(probs.cpu()).squeeze()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 179, in __call__
    return F.to_pil_image(pic, self.mode)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torchvision/transforms/functional.py", line 227, in to_pil_image
    raise ValueError('pic should not have > 4 channels. Got {} channels.'.format(pic.shape[-3]))
ValueError: pic should not have > 4 channels. Got 5 channels.

**Comment by milesial** [comment]
For now the predict script is mostly written to work for 1 or 2 classes. You would have to modify it to save the predictions to whatever format you prefer.
