### ISSUE TITLE
Training with x images while shown x + 1

### ISSUE THREAD

**Issue by NUS-Tim** [milesial/Pytorch-UNet#345]
Hi, I'm using my own dataset, however, when I train it, the error occurs:

```
Traceback (most recent call last):
  File "train.py", line 189, in <module>
    train_net(net=net,
  File "train.py", line 80, in train_net
    for batch in train_loader:
  File "C:\Users\Tim\.conda\envs\Segment\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "C:\Users\Tim\.conda\envs\Segment\lib\site-packages\torch\utils\data\dataloader.py", line 1204, in _next_data
    return self._process_data(data)
  File "C:\Users\Tim\.conda\envs\Segment\lib\site-packages\torch\utils\data\dataloader.py", line 1250, in _process_data
    data.reraise()
  File "C:\Users\Tim\.conda\envs\Segment\lib\site-packages\torch\_utils.py", line 457, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "C:\Users\Tim\.conda\envs\Segment\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\Tim\.conda\envs\Segment\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Tim\.conda\envs\Segment\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Tim\.conda\envs\Segment\lib\site-packages\torch\utils\data\dataset.py", line 471, in __getitem__
    return self.dataset[self.indices[idx]]
wandb: Waiting for W&B process to finish... (failed 1). Press Ctrl-C to abort syncing.
wandb:
wandb:
wandb: Run history:
wandb:      epoch ▁
wandb:       step ▁
wandb: train loss ▁
wandb:
wandb: Run summary:
wandb:      epoch 0
wandb:       step 1
wandb: train loss 1.4435
wandb:
wandb: Synced resilient-night-67: https://wandb.ai/carpetim/U-Net/runs/1vik4uh5
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: .\wandb\run-20220326_145040-1vik4uh5\logs
```

Then I try to check the problem, I find that the number of images it recognized is more than what I put in the data folder. For instance, if I only use 1 image to train, then it shows:

```
INFO: Creating dataset with 2 examples
```

There is no hidden file as I had checked. Thanks for your time :)

**Comment by milesial** [comment]
The images are detected with this line
https://github.com/milesial/Pytorch-UNet/blob/9a6ee84c50390306e24bb369d1c24d2fdd9d7e60/utils/data_loading.py#L20

So that means that `listdir` detects 2 images in your directory. What does `ls -la` show you?

**Comment by NUS-Tim** [comment]
Hi, milesial, sorry for the late reply. I actually had solved this, it's a weird bug, I find there is no hidden file when I use Windows terminal while I find a hidden file when using WSL2...... Anyway, thanks for your time. I will close the question.
