### ISSUE TITLE
about the predict.py

### ISSUE THREAD

**Issue by ASguoyue** [milesial/Pytorch-UNet#355]
when i run the predict.py , it has some mistakes:
Traceback (most recent call last):
  File "/home/atr2/Code/Pytorch-UNet-master/predict.py", line 101, in <module>
    img = Image.open(filename)
  File "/home/atr2/anaconda3/envs/PyTorch/lib/python3.7/site-packages/PIL/Image.py", line 2904, in open
    fp = builtins.open(filename, "rb")
IsADirectoryError: [Errno 21] Is a directory: '.'

I only change the data root, 
![image](https://user-images.githubusercontent.com/43775884/162218574-c7654265-ff03-46ca-9d8a-846ae7aa0375.png)

How can i deal with it, thanks.

**Comment by pleaseRedo** [comment]
I think it only works with imgs as input?

**Comment by LINFF1023** [comment]
How to test a whole folder of images？

**Comment by zlf179** [comment]
> How to test a whole folder of images？

just drag files into cmd

**Comment by LINFF1023** [comment]
> > How to test a whole folder of images？
> 
> just drag files into cmd

好像不行，，，

**Comment by 15982719597** [comment]
> How to test a whole folder of images？

Have you solved it, please? 
Now that I have trained the model, where should I adjust the path of my test set in "predict.py" if I want to predict my test set?

**Comment by leo1328** [comment]
用glob呗
