### ISSUE TITLE
How do I use tiff files in model training?

### ISSUE THREAD

**Issue by weltme** [milesial/Pytorch-UNet#360]
I want to use tiff files to train my model, how do I do that?
Looking for answers, thank you very much!

**Comment by weltme** [comment]
Traceback (most recent call last):
  File "D:/Pytorch-UNet-master/train.py", line 187, in <module>
    train_net(net=net,
  File "D:/Pytorch-UNet-master/train.py", line 95, in train_net
    loss = criterion(masks_pred, true_masks) \
  File "D:\ANACONDA3\envs\PyTorch\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\ANACONDA3\envs\PyTorch\lib\site-packages\torch\nn\modules\loss.py", line 1163, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "D:\ANACONDA3\envs\PyTorch\lib\site-packages\torch\nn\functional.py", line 2996, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: only batches of spatial targets supported (3D tensors) but got targets of size: : [4, 128, 128, 3]
python-BaseException

**Comment by Mountainsmaydepart** [comment]
I have the same problem
