### ISSUE TITLE
RuntimeError: number of dims don't match in permute

### ISSUE THREAD

**Issue by 40618233** [milesial/Pytorch-UNet#366]
Hi,I have this problem, can you help me?

Traceback (most recent call last):
  File "c:/Users/Hong/PycharmProjects/Pytorch-UNet-master/train.py", line 207, in <module>
    train_net(net=net,
  File "c:/Users/Hong/PycharmProjects/Pytorch-UNet-master/train.py", line 132, in train_net
    val_score = evaluate(net, val_loader, device)
  File "c:\Users\Hong\PycharmProjects\Pytorch-UNet-master\evaluate.py", line 19, in evaluate
    mask_true = F.one_hot(mask_true, net.n_classes).permute(256,256,256,256).float()
RuntimeError: number of dims don't match in permute

**Comment by Mountainsmaydepart** [comment]
> 

i think 
permute（256，256，256，256）
is wrongs
you can try to understand how permute is used
