### ISSUE TITLE
a problem in predict.py

### ISSUE THREAD

**Issue by Chen-je** [milesial/Pytorch-UNet#410]
Hi，i have a problem，i use VOC segmentation dataset to train a 21 classes net，but when i meet bellow problem， i change the ‘n_classes=21’。Look forward to your reply
Traceback (most recent call last):
  File "predict.py", line 124, in <module>
    mask = predict_img(net=net,
  File "predict.py", line 44, in predict_img
    full_mask = tf(probs.cpu()).squeeze()
  File "D:\software\anaconda3\envs\yolov5\lib\site-packages\torchvision\transforms\transforms.py", line 61, in __call__
    img = t(img)
  File "D:\software\anaconda3\envs\yolov5\lib\site-packages\torchvision\transforms\transforms.py", line 184, in __call__
    return F.to_pil_image(pic, self.mode)
  File "D:\software\anaconda3\envs\yolov5\lib\site-packages\torchvision\transforms\functional.py", line 243, in to_pil_image
    raise ValueError('pic should not have > 4 channels. Got {} channels.'.format(pic.shape[-3]))
ValueError: pic should not have > 4 channels. Got 21 channels.

**Comment by Chen-je** [comment]
maybe i need to write script for multiple predict...

**Comment by milesial** [comment]
Hi, can you try the latest master? I pushed a fix
