### ISSUE TITLE
train     Detected OutOfMemoryError

### ISSUE THREAD

**Issue by num-doc** [milesial/Pytorch-UNet#424]
ERROR: Detected OutOfMemoryError! Enabling checkpointing to reduce memory usage, but this slows down training. Consider enabling AMP (--amp) for fast and memory efficient training

win10
python 3.7 
torch-gpu  1.12
cuda 11.3
gtx  1080TI

**Comment by milesial** [comment]
You are running out of memory, please reduce the scaling of images, using a larger GPU of enabling AMP as the message suggests.

**Comment by num-doc** [comment]
Thanks for answering.
I don't think it is a problem of memory.Because I just use 30   640*640-pixel images. And i have run it successfully before with your code.
is it another possibility here?

**Comment by milesial** [comment]
Well the error is `Detected OutOfMemoryError!` so it is definitely a memory error. Check that nothing else is running on your GPU like UI or other workloads.

**Comment by willianLee** [comment]
train got error:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/lee/common/PycahrmProjects/Pytorch-UNet-master/train.py", line 43, in train_model
    dataset = CarvanaDataset(dir_img, dir_mask, img_scale)
  File "/media/lee/common/PycahrmProjects/Pytorch-UNet-master/utils/data_loading.py", line 118, in __init__
    super().__init__(images_dir, mask_dir, scale, mask_suffix='_mask')
  File "/media/lee/common/PycahrmProjects/Pytorch-UNet-master/utils/data_loading.py", line 54, in __init__
    unique = list(tqdm(
  File "/home/lee/anaconda3/envs/persondet/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/lee/anaconda3/envs/persondet/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/lee/common/PycahrmProjects/Pytorch-UNet-master/train.py", line 212, in <module>
    train_model(
  File "/media/lee/common/PycahrmProjects/Pytorch-UNet-master/train.py", line 45, in train_model
    dataset = BasicDataset(dir_img, dir_mask, img_scale)
  File "/media/lee/common/PycahrmProjects/Pytorch-UNet-master/utils/data_loading.py", line 59, in __init__
    self.mask_values = list(sorted(np.unique(np.concatenate(unique), axis=0).tolist()))
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 75 has 1 dimension(s)

**Comment by num-doc** [comment]
@willianLee

**Comment by num-doc** [comment]
@willianLee   I think you need to check the mapping between label and image, which may be a problem of initial configuration, such as checking the number of classes or whether label production is normal

**Comment by willianLee** [comment]
> 

thanks for this.
i got  new problem, when i set model channel=3, it report error:
AssertionError: Network has been defined with 3 input channels, but loaded images have 1 channels. Please check that the images are loaded correctly.

so i set model channel=1 and  got  error:
AssertionError: Network has been defined with 1 input channels, but loaded images have 3 channels. Please check that the images are loaded correctly.


It's a bit strange !

**Comment by HeartbeatD** [comment]
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
