### ISSUE TITLE
ValueError: autodetected range of [nan, nan] is not finite

### ISSUE THREAD

**Issue by NefarianZ** [milesial/Pytorch-UNet#429]
I run 500 epochs training, but after 200 epochs train finished, the train.py show below error. Please tell me how to solve it, thanks in adavnce.

Traceback (most recent call last):
  File "train.py", line 221, in <module>
    amp=args.amp
  File "train.py", line 140, in train_model
    histograms['Gradients/' + tag] = wandb.Histogram(value.grad.data.cpu())
  File "C:\ProgramData\Anaconda3\lib\site-packages\wandb\sdk\data_types\histogram.py", line 77, in __init__
    self.histogram, self.bins = np.histogram(sequence, bins=num_bins)
  File "<__array_function__ internals>", line 6, in histogram
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\histograms.py", line 793, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\histograms.py", line 426, in _get_bin_edges
    first_edge, last_edge = _get_outer_edges(a, range)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\histograms.py", line 324, in _get_outer_edges
    "autodetected range of [{}, {}] is not finite".format(first_edge, last_edge))
ValueError: autodetected range of [nan, nan] is not finite

**Comment by 15982719597** [comment]
我也有同样的问题，我准备跑300个epochs，但是在137的时候停下来了，错误是一样的。该怎么继续训练呢？

I had the same problem. I was going to run 300 epochs, but stopped at 137, and the error was the same. How to continue the training?

**Comment by milesial** [comment]
Hi, can you try the latest master?

**Comment by NefarianZ** [comment]
> 

Ok I will try it . Thanks

**Comment by 15982719597** [comment]
I am currently trying, have run 120/200epochs, there is no problem.

**Comment by NefarianZ** [comment]
> Hi, can you try the latest master?

It works bro. Thanks for your great work ^_^

**Comment by 15982719597** [comment]
![image](https://user-images.githubusercontent.com/101446325/222309933-67d97615-8452-49cd-9133-6a0b0d2e34b7.png)
Hello! 
I have tried the latest branch, but still made this error.

**Comment by milesial** [comment]
My bad I had a typo when checking gradients, it should be fixed now
