### ISSUE TITLE
RuntimeError: Trying to resize storage that is not resizable

### ISSUE THREAD

**Issue by Dharmendra04** [milesial/Pytorch-UNet#447]
Epoch 1/2:   0%|▋                                                                                                                                  | 80/16448 [00:16<54:40,  4.99img/s, loss (batch)=0.672]
Traceback (most recent call last):
  File "/home/dharmendra/Desktop/Unet/Pytorch-UNet/train.py", line 212, in <module>
    train_model(
  File "/home/dharmendra/Desktop/Unet/Pytorch-UNet/train.py", line 89, in train_model
    for batch in train_loader:
  File "/home/dharmendra/anaconda3/envs/yolov8_custom/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/dharmendra/anaconda3/envs/yolov8_custom/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1325, in _next_data
    return self._process_data(data)
  File "/home/dharmendra/anaconda3/envs/yolov8_custom/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/dharmendra/anaconda3/envs/yolov8_custom/lib/python3.9/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 20.
Original Traceback (most recent call last):
  File "/home/dharmendra/anaconda3/envs/yolov8_custom/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/dharmendra/anaconda3/envs/yolov8_custom/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/dharmendra/anaconda3/envs/yolov8_custom/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/home/dharmendra/anaconda3/envs/yolov8_custom/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 127, in collate
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "/home/dharmendra/anaconda3/envs/yolov8_custom/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 127, in <dictcomp>
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "/home/dharmendra/anaconda3/envs/yolov8_custom/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 119, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home/dharmendra/anaconda3/envs/yolov8_custom/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 161, in collate_tensor_fn
    out = elem.new(storage).resize_(len(batch), *list(elem.size()))
RuntimeError: Trying to resize storage that is not resizable

I am getting this issue when i am running the model, it is running for some iteration in the first epoch and showing this error, what might be the issue, masks and image having same number of files, masks are in .png and imgs are in jpg, additionally my mask is having 0 and 255 values only

**Comment by louisfacun** [comment]
I solved this issue by making sure the inputs are in square size.
