### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by BenjaminSchaar** [milesial/Pytorch-UNet#489]
(unet_test) benjaminschaar@A565-Benjamin-Mac Pytorch-UNet % python train.py
INFO: Using device cpu
INFO: Network:
	3 input channels
	2 output channels (classes)
	Transposed conv upscaling
INFO: Creating dataset with 110 examples
INFO: Scanning mask files to determine unique values
100%|█████████████████████████████████████████| 110/110 [00:32<00:00,  3.35it/s]
INFO: Unique mask values: [[0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4], [5, 5, 5], [6, 6, 6], [8, 8, 8], [10, 10, 10], [12, 12, 12], [14, 14, 14], [15, 15, 15], [17, 17, 17], [19, 19, 19], [21, 21, 21], [22, 22, 22], [24, 24, 24], [25, 25, 25], [27, 27, 27], [29, 29, 29], [30, 30, 30], [32, 32, 32], [33, 33, 33], [35, 35, 35], [36, 36, 36], [38, 38, 38], [39, 39, 39], [40, 40, 40], [42, 42, 42], [43, 43, 43], [45, 45, 45], [46, 46, 46], [47, 47, 47], [49, 49, 49], [50, 50, 50], [51, 51, 51], [53, 53, 53], [54, 54, 54], [55, 55, 55], [56, 56, 56], [58, 58, 58], [59, 59, 59], [60, 60, 60], [61, 61, 61], [63, 63, 63], [64, 64, 64], [65, 65, 65], [66, 66, 66], [68, 68, 68], [69, 69, 69], [70, 70, 70], [71, 71, 71], [72, 72, 72], [73, 73, 73], [75, 75, 75], [76, 76, 76], [77, 77, 77], [78, 78, 78], [79, 79, 79], [80, 80, 80], [82, 82, 82], [83, 83, 83], [84, 84, 84], [85, 85, 85], [86, 86, 86], [87, 87, 87], [88, 88, 88], [89, 89, 89], [90, 90, 90], [92, 92, 92], [93, 93, 93], [94, 94, 94], [95, 95, 95], [96, 96, 96], [97, 97, 97], [98, 98, 98], [99, 99, 99], [100, 100, 100], [101, 101, 101], [102, 102, 102], [103, 103, 103], [104, 104, 104], [105, 105, 105], [106, 106, 106], [107, 107, 107], [108, 108, 108], [110, 110, 110], [111, 111, 111], [112, 112, 112], [113, 113, 113], [114, 114, 114], [115, 115, 115], [116, 116, 116], [117, 117, 117], [118, 118, 118], [119, 119, 119], [120, 120, 120], [121, 121, 121], [122, 122, 122], [123, 123, 123], [124, 124, 124], [125, 125, 125], [126, 126, 126], [127, 127, 127], [128, 128, 128], [129, 129, 129], [130, 130, 130], [131, 131, 131], [132, 132, 132], [133, 133, 133], [134, 134, 134], [135, 135, 135], [136, 136, 136], [137, 137, 137], [138, 138, 138], [139, 139, 139], [140, 140, 140], [141, 141, 141], [142, 142, 142], [143, 143, 143], [144, 144, 144], [145, 145, 145], [146, 146, 146], [147, 147, 147], [148, 148, 148], [149, 149, 149], [150, 150, 150], [151, 151, 151], [152, 152, 152], [153, 153, 153], [154, 154, 154], [155, 155, 155], [156, 156, 156], [157, 157, 157], [158, 158, 158], [159, 159, 159], [160, 160, 160], [161, 161, 161], [162, 162, 162], [163, 163, 163], [164, 164, 164], [165, 165, 165], [166, 166, 166], [167, 167, 167], [168, 168, 168], [169, 169, 169], [170, 170, 170], [171, 171, 171], [172, 172, 172], [173, 173, 173], [174, 174, 174], [175, 175, 175], [176, 176, 176], [177, 177, 177], [178, 178, 178], [179, 179, 179], [180, 180, 180], [181, 181, 181], [182, 182, 182], [183, 183, 183], [184, 184, 184], [185, 185, 185], [186, 186, 186], [187, 187, 187], [188, 188, 188], [189, 189, 189], [190, 190, 190], [191, 191, 191], [192, 192, 192], [193, 193, 193], [194, 194, 194], [195, 195, 195], [196, 196, 196], [197, 197, 197], [198, 198, 198], [199, 199, 199], [200, 200, 200], [201, 201, 201], [202, 202, 202], [203, 203, 203], [204, 204, 204], [205, 205, 205], [206, 206, 206], [207, 207, 207], [208, 208, 208], [209, 209, 209], [210, 210, 210], [211, 211, 211], [212, 212, 212], [213, 213, 213], [214, 214, 214], [215, 215, 215], [216, 216, 216], [217, 217, 217], [218, 218, 218], [219, 219, 219], [220, 220, 220], [221, 221, 221], [222, 222, 222], [223, 223, 223], [224, 224, 224], [225, 225, 225], [226, 226, 226], [227, 227, 227], [228, 228, 228], [229, 229, 229], [230, 230, 230], [231, 231, 231], [232, 232, 232], [233, 233, 233], [234, 234, 234], [235, 235, 235], [236, 236, 236], [237, 237, 237], [238, 238, 238], [239, 239, 239], [240, 240, 240], [241, 241, 241], [242, 242, 242], [243, 243, 243], [244, 244, 244], [245, 245, 245], [246, 246, 246], [247, 247, 247], [248, 248, 248], [249, 249, 249], [250, 250, 250], [251, 251, 251], [252, 252, 252], [253, 253, 253], [254, 254, 254], [255, 255, 255]]
wandb: Currently logged in as: anony-mouse-710100656648280445. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.16.6
wandb: Run data is saved locally in /Users/benjaminschaar/Documents/GitHub/u_net/Pytorch-UNet/wandb/run-20240423_150007-eq0pkp6k
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run major-star-3
wandb: ⭐️ View project at https://wandb.ai/anony-mouse-710100656648280445/U-Net?apiKey=f4c911e74a581ca7f069408a11e024660ec7b048
wandb: 🚀 View run at https://wandb.ai/anony-mouse-710100656648280445/U-Net/runs/eq0pkp6k?apiKey=f4c911e74a581ca7f069408a11e024660ec7b048
wandb: WARNING Do NOT share these links with anyone. They can be used to claim your runs.
INFO: Starting training:
        Epochs:          5
        Batch size:      1
        Learning rate:   1e-05
        Training size:   99
        Validation size: 11
        Checkpoints:     True
        Device:          cpu
        Images scaling:  0.5
        Mixed Precision: False

Epoch 1/5:   0%|                                        | 0/99 [00:22<?, ?img/s]
Traceback (most recent call last):
  File "train.py", line 213, in <module>
    train_model(
  File "train.py", line 106, in train_model
    loss = criterion(masks_pred, true_masks)
  File "/Users/benjaminschaar/anaconda3/envs/unet_test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/benjaminschaar/anaconda3/envs/unet_test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/benjaminschaar/anaconda3/envs/unet_test/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1179, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/Users/benjaminschaar/anaconda3/envs/unet_test/lib/python3.8/site-packages/torch/nn/functional.py", line 3059, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
IndexError: Target 231 is out of bounds.
wandb: 🚀 View run major-star-3 at: https://wandb.ai/anony-mouse-710100656648280445/U-Net/runs/eq0pkp6k?apiKey=f4c911e74a581ca7f069408a11e024660ec7b048
wandb: ⭐️ View project at: https://wandb.ai/anony-mouse-710100656648280445/U-Net?apiKey=f4c911e74a581ca7f069408a11e024660ec7b048
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240423_150007-eq0pkp6k/logs

I dont Know why I get this error, i am using my own dataset with rgb masks and images

**Comment by bayueyaoshao** [comment]
The input images and target masks should be in the data/imgs and data/masks folders respectively (note that the imgs and masks folder should not contain any sub-folder or any other files, due to the greedy data-loader). For Carvana, images are RGB and masks are black and white.
