### ISSUE TITLE
train.py RuntimeError: expected input[1, 1, 307, 409] to have 3 channels, but got 1 channels instead

### ISSUE THREAD

**Issue by alkeksibusiii** [milesial/Pytorch-UNet#86]
kirsch@imflow:~/Pytorch-UNet-master$ python3 train.py 
INFO: Using device cuda
INFO: Network:
	3 input channels
	1 output channels (classes)
	Bilinear upscaling
INFO: Starting training:
        Epochs:          5
        Batch size:      1
        Learning rate:   0.1
        Training size:   156
        Validation size: 27
        Checkpoints:     True
        Device:          cuda
        Images scaling:  0.5
    
Epoch 1/5:   3%|██▋                                                                                 | 5/156 [00:00<00:20,  7.19img/s, loss (batch)=0.0738]
Traceback (most recent call last):
  File "train.py", line 164, in <module>
    val_percent=args.val / 100)
  File "train.py", line 71, in train_net
    masks_pred = net(imgs)
  File "/home/kirsch/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirsch/Pytorch-UNet-master/unet/unet_model.py", line 27, in forward
    x1 = self.inc(x)
  File "/home/kirsch/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirsch/Pytorch-UNet-master/unet/unet_parts.py", line 23, in forward
    return self.double_conv(x)
  File "/home/kirsch/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirsch/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/kirsch/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirsch/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/kirsch/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 64 3 3 3, expected input[1, 1, 307, 409] to have 3 channels, but got 1 channels instead

**Comment by milesial** [comment]
If your inputs have only 1 channel, change n_channels=1 in the network creation

**Comment by alkeksibusiii** [comment]
ok thanks for the hint, training is working now! there was also a mix of sRGB / greyscale images in my own data, hence the error.
